First project info
openhwgroup/advanced-riscv-verification-methodologies pull request #2
Opened 2022-10-21 18:49 UTC by simon5656

2022-10-21 19:45 UTC, DBees commented
@simon5656 as agreed the monthly reports are to live in https://github.com/openhwgroup/program/TGs/verification-task-group/Monthly-Reports

Please don't put them here

2022-10-21 22:36 UTC, DBees commented
As mentioned above the project reports don't belong in this repo, they should go in the programs repo

2022-10-22 11:12 UTC, simon5656 commented
as I have said - when you have sorted out the structure of the programs repo I will move them - please don't delay this repo until you sort the other one - please merge this now.

2022-10-23 20:51 UTC, DBees commented
Hi Simon

It is created as we discussed via merged pull request. The structure is there… down to  <https://github.com/openhwgroup/programs> programs/ <https://github.com/openhwgroup/programs/tree/master/TGs> TGs/ <https://github.com/openhwgroup/programs/tree/master/TGs/verification-task-group> verification-task-group/Project-Reports/ and  <https://github.com/openhwgroup/programs/tree/master/TGs/verification-task-group/Meetings> https://github.com/openhwgroup/programs/tree/master/TGs/verification-task-group/Meetings

 

However as there is also legacy stuff in there, please work with Mike to sort out what legacy stuff should be kept and what should be folded into which folder, keeping mind the agreed structure. Or if you both want to meet with me and sort through it together, I’m happy to do the cleanup. I would strongly prefer that we put the new files into the new agreed structure to start in the right direction. 

Duncan

 



 

You’ll note within the verification-task-group there are several extraneous folders from before. Please decide with Mike what to keep and what to chuck away or how to sort those.

 

I would really rather not merge into the other repo as I’m pretty sure once we start one way it will be harder to  

 

From: Simon Davidmann ***@***.***> 
Sent: October 22, 2022 4:13 AM
To: openhwgroup/advanced-riscv-verification-methodologies ***@***.***>
Cc: DBees ***@***.***>; Comment ***@***.***>
Subject: Re: [openhwgroup/advanced-riscv-verification-methodologies] First project info (PR #2)

 

as I have said - when you have sorted out the structure of the programs repo I will move them - please don't delay this repo until you sort the other one - please merge this now.

—
Reply to this email directly, view it on GitHub <https://github.com/openhwgroup/advanced-riscv-verification-methodologies/pull/2#issuecomment-1287763057> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/ACEIERUL5B4WNS5Y7Z3FZO3WEPD4HANCNFSM6AAAAAARLNPJJU> .
You are receiving this because you commented.  <https://github.com/notifications/beacon/ACEIERVDUA3ELF35HC4WBOLWEPD4HA5CNFSM6AAAAAARLNPJJWWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSMYG2HC.gif> Message ID: ***@***.*** ***@***.***> >

2022-10-26 11:56 UTC, simon5656 commented
updated with second data sets

2022-10-26 13:00 UTC, simon5656 commented
updated to add zfinx

2022-10-26 17:52 UTC, MikeOpenHWGroup requested changes
Please remove [2022-Aug10-ARVM-Advanced-riscv-Verification-Methodologies-OpenHW-Project-Concept-Proposal.md](ARVM-TopProject/2022-Aug10-ARVM-Advanced-riscv-Verification-Methodologies-OpenHW-Project-Concept-Proposal.md) as this is already in `openhwgroup/programs`.

2022-10-27 08:07 UTC, simon5656 commented
resolved - pls merge

2022-10-27 15:56 UTC, MikeOpenHWGroup approved these changes
LGTM, thanks @simon5656.   @DBees, let me know if you have any outstanding items.

2022-10-27 15:56 UTC, MikeOpenHWGroup commented on ARVM-TopProject/2022-Aug10-ARVM-Advanced-riscv-Verification-Methodologies-OpenHW-Project-Concept-Proposal.md
> +# OpenHW Project Concept Proposal:
Please delete this file (already in `openhwgroup/programs`).

2022-10-27 15:56 UTC, MikeOpenHWGroup commented on ARVM-TopProject/README.md
> +The project proposal is here: [2022-Aug10-ARVM-Advanced-riscv-Verification-Methodologies-OpenHW-Project-Concept-Proposal.md](2022-Aug10-ARVM-Advanced-riscv-Verification-Methodologies-OpenHW-Project-C
Point to `openhwgroup/programs`.

2022-10-27 15:56 UTC, MikeOpenHWGroup commented on ARVM-TopProject/2022-Aug10-ARVM-Advanced-riscv-Verification-Methodologies-OpenHW-Project-Concept-Proposal.md
> +# OpenHW Project Concept Proposal:
Thanks

2022-10-27 15:56 UTC, MikeOpenHWGroup commented on ARVM-TopProject/README.md
> +The project proposal is here: [2022-Aug10-ARVM-Advanced-riscv-Verification-Methodologies-OpenHW-Project-Concept-Proposal.md](2022-Aug10-ARVM-Advanced-riscv-Verification-Methodologies-OpenHW-Project-C
Thanks

2022-11-02 14:18 UTC, MikeOpenHWGroup approved these changes

2022-11-02 14:22 UTC, MikeOpenHWGroup requested changes
The coverage log files (e.g. `ARVM-FunctionalCoverage/20221019/RV32F-20221019/RV32F_SystemVerilog-coverage.log` are machine generated and of very little practical use.  These should not be check into the repo.

2022-11-02 14:26 UTC, MikeOpenHWGroup reviewed
Why are the coverage models in files with SVH extensions?   They are not header files, there are primarily covergroups, so I would expect them to be in files with an SV extension.

2022-11-02 14:33 UTC, MikeOpenHWGroup requested changes
Recommend renaming the "coverage" spreadsheets (e.g. `ARVM-FunctionalCoverage/20221019/RV32F-20221019/RV32F_coverage.csv`) to something that indicates they are coverage _specifications_, not coverage implementations.

The core-v-verif nominature for these is "DVplan", so I would suggest `RV32F_DVplan.csv`.

2022-11-02 14:33 UTC, MikeOpenHWGroup commented on ARVM-FunctionalCoverage/20221102/sv_coverage_CV32E40Pv2/coverage/RISCV_coverage_pkg.svh
> +//
Package files should not have an SVH extension.

2022-11-02 18:30 UTC, simon5656 commented
the coverage log files are example of what the coverage actually looks like when run through a simulator -  as the code in SystemVerilog does not show the bins etc and while developing functional coverage it is essential to see things like this

this file is temporary - as was felt useful to be shown and walked through - and as all these files are - and if you like I will just put things into other public repos to save you the review issues... - where is the repo for work in progress... it is this one.
________________________________
From: Mike Thompson ***@***.***>
Sent: 02 November 2022 14:22
To: openhwgroup/advanced-riscv-verification-methodologies ***@***.***>
Cc: Simon Davidmann ***@***.***>; Mention ***@***.***>
Subject: Re: [openhwgroup/advanced-riscv-verification-methodologies] First project info (PR #2)


@MikeOpenHWGroup requested changes on this pull request.

The coverage log files (e.g. ARVM-FunctionalCoverage/20221019/RV32F-20221019/RV32F_SystemVerilog-coverage.log are machine generated and of very little practical use. These should not be check into the repo.

—
Reply to this email directly, view it on GitHub<https://github.com/openhwgroup/advanced-riscv-verification-methodologies/pull/2#pullrequestreview-1165347359>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AA3V7ZDV3GGSS2MEZUM27TTWGJ2KBANCNFSM6AAAAAARLNPJJU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-11-02 18:31 UTC, simon5656 commented
they are files that are included... and normally if a file is included it is a termed a header and thus .svh

this repo directory is temporary - as was felt useful to be shown and walked through - and as all these files are - and if you like I will just put things into other public repos to save you the review issues... - where is the repo for work in progress... it is this one.
________________________________
From: Mike Thompson ***@***.***>
Sent: 02 November 2022 14:26
To: openhwgroup/advanced-riscv-verification-methodologies ***@***.***>
Cc: Simon Davidmann ***@***.***>; Mention ***@***.***>
Subject: Re: [openhwgroup/advanced-riscv-verification-methodologies] First project info (PR #2)


@MikeOpenHWGroup commented on this pull request.

Why are the coverage models in files with SVH extensions? They are not header files, there are primarily covergroups, so I would expect them to be in files with an SV extension.

—
Reply to this email directly, view it on GitHub<https://github.com/openhwgroup/advanced-riscv-verification-methodologies/pull/2#pullrequestreview-1165355360>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AA3V7ZEJJYMD3EINODUSQLTWGJ2Y7ANCNFSM6AAAAAARLNPJJU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-11-02 18:32 UTC, simon5656 commented
this repo directory is temporary - as was felt useful to be shown and walked through - and as all these files are - and if you like I will just put things into other public repos to save you the review issues... - where is the repo for work in progress... it is this one.

________________________________
From: Mike Thompson ***@***.***>
Sent: 02 November 2022 14:33
To: openhwgroup/advanced-riscv-verification-methodologies ***@***.***>
Cc: Simon Davidmann ***@***.***>; Mention ***@***.***>
Subject: Re: [openhwgroup/advanced-riscv-verification-methodologies] First project info (PR #2)


@MikeOpenHWGroup requested changes on this pull request.

Recommend renaming the "coverage" spreadsheets (e.g. ARVM-FunctionalCoverage/20221019/RV32F-20221019/RV32F_coverage.csv) to something that indicates they are coverage specifications, not coverage implementations.

The core-v-verif nominature for these is "DVplan", so I would suggest RV32F_DVplan.csv.

________________________________

In ARVM-FunctionalCoverage/20221102/sv_coverage_CV32E40Pv2/coverage/RISCV_coverage_pkg.svh<https://github.com/openhwgroup/advanced-riscv-verification-methodologies/pull/2#discussion_r1011848294>:

> @@ -0,0 +1,105 @@
+//


Package files should not have an SVH extension.

—
Reply to this email directly, view it on GitHub<https://github.com/openhwgroup/advanced-riscv-verification-methodologies/pull/2#pullrequestreview-1165359160>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AA3V7ZARVFJK5D6OKPBOXLDWGJ3VHANCNFSM6AAAAAARLNPJJU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-11-02 18:55 UTC, simon5656 commented
From Dave Rich...
The typical convention is that .sv files are placed on the compilers command line, whereas .svh files are read by `include directives from other files

The only files that should be read by `include are macro `defines and design units that are split into multiple files for collaborative source control. For example, each class in a package is typically put into a separate file. You may want to read my post about `include versus import: http://go.mentor.com/package-import-versus-include"
________________________________
From: Mike Thompson ***@***.***>
Sent: 02 November 2022 14:26
To: openhwgroup/advanced-riscv-verification-methodologies ***@***.***>
Cc: Simon Davidmann ***@***.***>; Mention ***@***.***>
Subject: Re: [openhwgroup/advanced-riscv-verification-methodologies] First project info (PR #2)


@MikeOpenHWGroup commented on this pull request.

Why are the coverage models in files with SVH extensions? They are not header files, there are primarily covergroups, so I would expect them to be in files with an SV extension.

—
Reply to this email directly, view it on GitHub<https://github.com/openhwgroup/advanced-riscv-verification-methodologies/pull/2#pullrequestreview-1165355360>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AA3V7ZEJJYMD3EINODUSQLTWGJ2Y7ANCNFSM6AAAAAARLNPJJU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-11-02 19:01 UTC, simon5656 commented
"Once the code is in multiple files, we use different file extensions to help us remember if the file needs to be put on the compiler's command line or will be `included from the source of another file. We use the 'h' suffix to indicate a file to be `included mainly because that the convention in many other programming languages. 'h' stands for header, or the prototypes of routines without their implementation. SystemVerilog does not really have the same need for header files, but people still the 'header' terminology to indicate a file that needs to be `included."

With this rationale, (which is good), all the files included in a package should have a .svh extension. In practice, I have seen many cases where people don't do this.
________________________________
From: Mike Thompson ***@***.***>
Sent: 02 November 2022 14:26
To: openhwgroup/advanced-riscv-verification-methodologies ***@***.***>
Cc: Simon Davidmann ***@***.***>; Mention ***@***.***>
Subject: Re: [openhwgroup/advanced-riscv-verification-methodologies] First project info (PR #2)


@MikeOpenHWGroup commented on this pull request.

Why are the coverage models in files with SVH extensions? They are not header files, there are primarily covergroups, so I would expect them to be in files with an SV extension.

—
Reply to this email directly, view it on GitHub<https://github.com/openhwgroup/advanced-riscv-verification-methodologies/pull/2#pullrequestreview-1165355360>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AA3V7ZEJJYMD3EINODUSQLTWGJ2Y7ANCNFSM6AAAAAARLNPJJU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-11-04 01:04 UTC, MikeOpenHWGroup commented
> the coverage log files are example of what the coverage actually looks like when run through a simulator -  as the code in SystemVerilog does not show the bins etc and while developing functional coverage it is essential to see things like this.

Understood and I agree that it is important to be able to generate and review these files.  However, as these files are machine-generated there is no need to have then in a version control repository.  When a developer needs to see the results of a sim they will review the coverage logs they generate, not the coverage logs in a repo generated by someone else.

2022-11-04 01:05 UTC, MikeOpenHWGroup commented
> From Dave Rich...
The typical convention is that .sv files are placed on the compilers command line, whereas .svh files are read by `include directives from other files

OK, I'll play ball with that.

2022-11-04 01:14 UTC, MikeOpenHWGroup commented
AFAICT, then are only two remaining unresolved points in this review:
1. Recommend renaming the "coverage" spreadsheets (e.g. ARVM-FunctionalCoverage/20221019/RV32F-20221019/RV32F_coverage.csv) to something that indicates they are coverage specifications, not coverage implementations. The core-v-verif nominature for these is "DVplan", so I would suggest RV32F_DVplan.csv.
2. Inclusion of the coverage log files (e.g. `RV32F_SystemVerilog-coverage.log`).

We can deal with the first item in a separate pull-request.   However, the coverage logfile should not be merged in.  Please delete and we are good-to-merge.

2022-11-04 11:35 UTC, simon5656 commented
yes but until they have some code that works they need to know what is going to be there so these are temporary and for information like lots of other documentation.

________________________________
From: Mike Thompson ***@***.***>
Sent: 04 November 2022 01:04
To: openhwgroup/advanced-riscv-verification-methodologies ***@***.***>
Cc: Simon Davidmann ***@***.***>; Mention ***@***.***>
Subject: Re: [openhwgroup/advanced-riscv-verification-methodologies] First project info (PR #2)


the coverage log files are example of what the coverage actually looks like when run through a simulator - as the code in SystemVerilog does not show the bins etc and while developing functional coverage it is essential to see things like this.

Understood and I agree that it is important to be able to generate and review these files. However, as these files are machine-generated there is no need to have then in a version control repository. When a developer needs to see the results of a sim they will review the coverage logs they generate, not the coverage logs in a repo generated by someone else.

—
Reply to this email directly, view it on GitHub<https://github.com/openhwgroup/advanced-riscv-verification-methodologies/pull/2#issuecomment-1302838175>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AA3V7ZAPGM53UYZDJ7KJO63WGROKJANCNFSM6AAAAAARLNPJJU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-11-04 11:39 UTC, simon5656 commented
these .csv files are temporary - to document the development - as we develop the spec of what should be documented we can work on this - for example I think we will not use .csv but write out .md for github for easy of browsing etc and maybe one .xslx for all the extensions in a different tab etc - so again the name is irrelevant - the content is the thing to focus on.

I would far prefer all the comments to be related the work like for example missing coverpoints...


________________________________
From: Mike Thompson ***@***.***>
Sent: 04 November 2022 01:14
To: openhwgroup/advanced-riscv-verification-methodologies ***@***.***>
Cc: Simon Davidmann ***@***.***>; Mention ***@***.***>
Subject: Re: [openhwgroup/advanced-riscv-verification-methodologies] First project info (PR #2)


AFAICT, then are only two remaining unresolved points in this review:

  1.  Recommend renaming the "coverage" spreadsheets (e.g. ARVM-FunctionalCoverage/20221019/RV32F-20221019/RV32F_coverage.csv) to something that indicates they are coverage specifications, not coverage implementations. The core-v-verif nominature for these is "DVplan", so I would suggest RV32F_DVplan.csv.
  2.  Inclusion of the coverage log files (e.g. RV32F_SystemVerilog-coverage.log).

We can deal with the first item in a separate pull-request. However, the coverage logfile should not be merged in. Please delete and we are good-to-merge.

—
Reply to this email directly, view it on GitHub<https://github.com/openhwgroup/advanced-riscv-verification-methodologies/pull/2#issuecomment-1302842568>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AA3V7ZCUAKXFFJCS22ZEDN3WGRPQPANCNFSM6AAAAAARLNPJJU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-11-04 12:30 UTC, MikeOpenHWGroup commented
> these .csv files are temporary - to document the development

Ah, I did not understand this.  We should make that clear in a README in the same directory.

> yes but until they have some code that works they need to know what is going to be there so these are temporary and for information like lots of other documentation.

I assume this comment relates to the coverage log file.  There is simply no need for these and dumping large, machine generatable files into GitHub is no useful.

2022-12-01 09:26 UTC, silabs-robin commented
> the coverage log files are example of what the coverage actually looks like when run through a simulator

Fair point, that is useful info when browsing a repo.

Could it be reduced to code snippets in a readme?

2022-12-01 09:57 UTC, silabs-robin commented
> Recommend renaming the "coverage" spreadsheets (e.g. ARVM-FunctionalCoverage/20221019/RV32F-20221019/RV32F_coverage.csv) to something that indicates they are coverage specifications

> these .csv files are temporary - to document the development

> Ah, I did not understand this. We should make that clear in a README in the same directory.

Is this solved?

_(My 2 cents: if a repo is not structured properly it will just become unnavigable and people abstain from using it. This includes intelligible naming.)_

2022-12-05 16:11 UTC, MikeOpenHWGroup requested changes
Looks good, thanks for this!  One serious comment and several minor ones.  The serious comment is that there are at least two files which declare that Imperas holds the copyright, but do not indicate a permissive license.  We cannot accept these into an OpenHW repo.  (I'm sure it was just a simple oversight.)

The other comments are asking for the addition of an SPDX header.

2022-12-05 16:11 UTC, MikeOpenHWGroup commented on ARVM-FunctionalCoverage/20221201/CV32E40Pv2_riscvISACOV/ChangeLog.md
> +Copyright (c) 2005-2022 Imperas Software Ltd., www.imperas.com
We cannot accept a copyright file into an OpenHW repo unless it is permissively licensed, ideally with Solderpad-2.0 or Apache-2.- (or newer).

2022-12-05 16:11 UTC, MikeOpenHWGroup commented on ARVM-FunctionalCoverage/20221201/CV32E40Pv2_riscvISACOV/source/RISCV_coverage_config.svh
> +// Copyright (c) 2022 Imperas Software Ltd., www.imperas.com
Please also add an SPDX header:
```
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.0
```

For future reference, all that is needed are the Copyright and SPDX statements:
```
// Copyright (c) 2022 Imperas Software Ltd., www.imperas.com
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.0
```

2022-12-05 16:11 UTC, MikeOpenHWGroup commented on ARVM-FunctionalCoverage/20221201/CV32E40Pv2_riscvISACOV/source/coverage/RISCV_coverage_pkg.svh
> +// Copyright (c) 2022 Imperas Software Ltd., www.imperas.com
SPDX

2022-12-05 16:11 UTC, MikeOpenHWGroup commented on ARVM-FunctionalCoverage/20221201/CV32E40Pv2_riscvISACOV/source/coverage/RV32F_illegal_coverage.svh
> +// Copyright (c) 2022 Imperas Software Ltd., www.imperas.com
SPDX

2022-12-05 16:11 UTC, MikeOpenHWGroup commented on ARVM-FunctionalCoverage/20221201/CV32E40Pv2_riscvISACOV/source/coverage/RV32ZCFZFINX_illegal_coverage.svh
> +// Copyright (c) 2022 Imperas Software Ltd., www.imperas.com
SPDX

2022-12-05 16:11 UTC, MikeOpenHWGroup commented on ARVM-FunctionalCoverage/20221201/CV32E40S_riscvISACOV/ChangeLog.md
> +Copyright (c) 2005-2022 Imperas Software Ltd., www.imperas.com
Please add permissive license header.

2022-12-05 16:11 UTC, MikeOpenHWGroup commented on ARVM-FunctionalCoverage/20221201/CV32E40S_riscvISACOV/source/RISCV_coverage_config.svh
> +// Copyright (c) 2022 Imperas Software Ltd., www.imperas.com
SPDX

2022-12-05 16:11 UTC, MikeOpenHWGroup commented on ARVM-FunctionalCoverage/20221201/CV32E40S_riscvISACOV/source/coverage/RISCV_coverage_common.svh
> +        $error("Cannot select both COVER_BASE_RV32I and COVER_BASE_RV32E!");
Can we make these `$fatal()`?.

2022-12-05 16:11 UTC, MikeOpenHWGroup commented on ARVM-FunctionalCoverage/20221201/CV32E40S_riscvISACOV/source/coverage/RISCV_coverage_pkg.svh
> +// Copyright (c) 2022 Imperas Software Ltd., www.imperas.com
SPDX

2022-12-13 11:58 UTC, silabs-robin commented
@simon5656, @MikeOpenHWGroup, it seems the copyright headers are the only remaining issue blocking this PR?

2022-12-13 16:03 UTC, MikeOpenHWGroup commented
> @simon5656, @MikeOpenHWGroup, it seems the copyright headers are the only remaining issue blocking this PR?

That is the big one.  I'd also like to see the $error() calls replaced with $fatal().  If the user misconfigs the compiler macros the whole thing should terminate at t=0.

2022-12-20 09:07 UTC, silabs-robin commented
> > @simon5656, @MikeOpenHWGroup, it seems the copyright headers are the only remaining issue blocking this PR?
> 
> That is the big one. I'd also like to see the $error() calls replaced with $fatal().
> 
> How quickly do you need this?

We would kinda need it now. @MikeOpenHWGroup 

Because afterwards, there will be a job to connect this Zc coverage up in core-v-verif to get some actual metrics out of it.
And after that, there will be a job to process the metrics, potentially tweaking constrained random or waiving.
So any delay before that will just push us too far into the future.

I know it is christmas times, but those changes above are fairly small. @simon5656, any chance of fixing it this week?

2022-12-22 15:10 UTC, simon5656 commented
fixed error->fatal and SPDX header. in pull request

2022-12-22 15:52 UTC, MikeOpenHWGroup approved these changes

2022-12-22 15:53 UTC, MikeOpenHWGroup commented
Thanks for the updates @simon5656.   Merging...

2022-12-22 15:53 UTC, merged

2022-12-22 15:59 UTC, silabs-robin commented
Excellent! Thank you both. 🙇‍♂️